# Generated by Django 3.1.4 on 2020-12-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link_button',
            field=models.URLField(default=None, max_length=255),
        ),
    ]
