# Generated by Django 3.1.4 on 2020-12-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='subs_count',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
